#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

module Enums
  # forward declarations

  # enums
  module FooEnum
    include ::ProtocolBuffers::Enum

    set_fully_qualified_name "enums.FooEnum"

    ONE = 1
    TWO = 2
    THREE = 3
  end

  module BarEnum
    include ::ProtocolBuffers::Enum

    # purposfully removing qualified name to make sure nothing breaks
    #set_fully_qualified_name "enums.BarEnum"

    FOUR = 4
    FIVE = 5
    SIX = 6
  end

end
