#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

# forward declarations
class A
  include ProtocolBuffers::Message
end
class C
  include ProtocolBuffers::Message
end

class A
  include ProtocolBuffers::Message

  # forward declarations
  class B
    include ProtocolBuffers::Message
  end

  set_fully_qualified_name "A"

  # nested messages
  class B
    set_fully_qualified_name "A.B"
  end

  optional ::A::B, :b, 1
end

class C
  include ProtocolBuffers::Message

  # purposefully removing qualified name to make sure that nothing breaks
  #set_fully_qualified_name "C"

  optional ::A::B, :b, 1
end

