#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

module Simple
  # forward declarations
  class Test1
    include ProtocolBuffers::Message
  end
  class Foo
    include ProtocolBuffers::Message
  end
  class Bar
    include ProtocolBuffers::Message
  end

  class Test1
    include ProtocolBuffers::Message

    set_fully_qualified_name "simple.Test1"

    optional :string, :test_field, 1
  end

  class Foo
    include ProtocolBuffers::Message

    set_fully_qualified_name "simple.Foo"

  end

  class Bar
    include ProtocolBuffers::Message

    # purposefully removing qualified name to make sure that nothing breaks
    #set_fully_qualified_name "simple.Bar"

    optional ::Simple::Foo, :foo, 1
  end

end
