#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

module Simple
  # forward declarations
  class Test1 < ::ProtocolBuffers::Message; end
  class Foo < ::ProtocolBuffers::Message; end
  class Bar < ::ProtocolBuffers::Message; end

  class Test1 < ::ProtocolBuffers::Message
    optional :string, :test_field, 1
  end

  class Foo < ::ProtocolBuffers::Message
  end

  class Bar < ::ProtocolBuffers::Message
    optional ::Simple::Foo, :foo, 1
  end

end
